// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package authority

import (
	context "context"
	model "github.com/ez-deploy/protobuf/model"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OpsClient is the client API for Ops service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpsClient interface {
	SetAuthorities(ctx context.Context, in *Authorities, opts ...grpc.CallOption) (*model.CommonResp, error)
	ListAuthoritiesByIdentity(ctx context.Context, in *model.Identity, opts ...grpc.CallOption) (*ListAuthoritiesResp, error)
	ListAuthoritiesByResource(ctx context.Context, in *model.Resource, opts ...grpc.CallOption) (*ListAuthoritiesResp, error)
	DeleteAuthorities(ctx context.Context, in *Authorities, opts ...grpc.CallOption) (*DeleteAuthoritiesResp, error)
}

type opsClient struct {
	cc grpc.ClientConnInterface
}

func NewOpsClient(cc grpc.ClientConnInterface) OpsClient {
	return &opsClient{cc}
}

func (c *opsClient) SetAuthorities(ctx context.Context, in *Authorities, opts ...grpc.CallOption) (*model.CommonResp, error) {
	out := new(model.CommonResp)
	err := c.cc.Invoke(ctx, "/Ops/SetAuthorities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsClient) ListAuthoritiesByIdentity(ctx context.Context, in *model.Identity, opts ...grpc.CallOption) (*ListAuthoritiesResp, error) {
	out := new(ListAuthoritiesResp)
	err := c.cc.Invoke(ctx, "/Ops/ListAuthoritiesByIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsClient) ListAuthoritiesByResource(ctx context.Context, in *model.Resource, opts ...grpc.CallOption) (*ListAuthoritiesResp, error) {
	out := new(ListAuthoritiesResp)
	err := c.cc.Invoke(ctx, "/Ops/ListAuthoritiesByResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsClient) DeleteAuthorities(ctx context.Context, in *Authorities, opts ...grpc.CallOption) (*DeleteAuthoritiesResp, error) {
	out := new(DeleteAuthoritiesResp)
	err := c.cc.Invoke(ctx, "/Ops/DeleteAuthorities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpsServer is the server API for Ops service.
// All implementations must embed UnimplementedOpsServer
// for forward compatibility
type OpsServer interface {
	SetAuthorities(context.Context, *Authorities) (*model.CommonResp, error)
	ListAuthoritiesByIdentity(context.Context, *model.Identity) (*ListAuthoritiesResp, error)
	ListAuthoritiesByResource(context.Context, *model.Resource) (*ListAuthoritiesResp, error)
	DeleteAuthorities(context.Context, *Authorities) (*DeleteAuthoritiesResp, error)
	mustEmbedUnimplementedOpsServer()
}

// UnimplementedOpsServer must be embedded to have forward compatible implementations.
type UnimplementedOpsServer struct {
}

func (UnimplementedOpsServer) SetAuthorities(context.Context, *Authorities) (*model.CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAuthorities not implemented")
}
func (UnimplementedOpsServer) ListAuthoritiesByIdentity(context.Context, *model.Identity) (*ListAuthoritiesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAuthoritiesByIdentity not implemented")
}
func (UnimplementedOpsServer) ListAuthoritiesByResource(context.Context, *model.Resource) (*ListAuthoritiesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAuthoritiesByResource not implemented")
}
func (UnimplementedOpsServer) DeleteAuthorities(context.Context, *Authorities) (*DeleteAuthoritiesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAuthorities not implemented")
}
func (UnimplementedOpsServer) mustEmbedUnimplementedOpsServer() {}

// UnsafeOpsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpsServer will
// result in compilation errors.
type UnsafeOpsServer interface {
	mustEmbedUnimplementedOpsServer()
}

func RegisterOpsServer(s grpc.ServiceRegistrar, srv OpsServer) {
	s.RegisterService(&Ops_ServiceDesc, srv)
}

func _Ops_SetAuthorities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Authorities)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServer).SetAuthorities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ops/SetAuthorities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServer).SetAuthorities(ctx, req.(*Authorities))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ops_ListAuthoritiesByIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.Identity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServer).ListAuthoritiesByIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ops/ListAuthoritiesByIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServer).ListAuthoritiesByIdentity(ctx, req.(*model.Identity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ops_ListAuthoritiesByResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.Resource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServer).ListAuthoritiesByResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ops/ListAuthoritiesByResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServer).ListAuthoritiesByResource(ctx, req.(*model.Resource))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ops_DeleteAuthorities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Authorities)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServer).DeleteAuthorities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ops/DeleteAuthorities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServer).DeleteAuthorities(ctx, req.(*Authorities))
	}
	return interceptor(ctx, in, info, handler)
}

// Ops_ServiceDesc is the grpc.ServiceDesc for Ops service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ops_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Ops",
	HandlerType: (*OpsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetAuthorities",
			Handler:    _Ops_SetAuthorities_Handler,
		},
		{
			MethodName: "ListAuthoritiesByIdentity",
			Handler:    _Ops_ListAuthoritiesByIdentity_Handler,
		},
		{
			MethodName: "ListAuthoritiesByResource",
			Handler:    _Ops_ListAuthoritiesByResource_Handler,
		},
		{
			MethodName: "DeleteAuthorities",
			Handler:    _Ops_DeleteAuthorities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authority/authority.proto",
}
